-- Plantillas importadas desde OAs templados.xls. Ejecutar despu?s de 014.

create table if not exists public.analysis_package_rows (
  package_id uuid not null references public.analysis_packages(id) on delete cascade,
  row_key text not null,
  label text not null,
  unit text,
  row_type text not null default 'result' check (row_type in ('result', 'aggregate')),
  aggregation text,
  display_order integer not null,
  primary key (package_id, row_key),
  unique (package_id, display_order)
);

insert into public.analysis_packages (code, name, active, package_type, duration) values
  ('XLS-01', 'NOM-002-SEMARNAT-1996 INSTANT', true, 'norma', 'instant'::public.package_duration),
  ('XLS-02', 'NOM-002-SEMARNAT-1996 12H', true, 'norma', '12H'::public.package_duration),
  ('XLS-03', 'NOM-002-SEMARNAT-1996 24H', true, 'norma', '24H'::public.package_duration),
  ('XLS-04', 'NOM-002-1996 + DQO INSTANT', true, 'norma', 'instant'::public.package_duration),
  ('XLS-05', 'NOM-002-1996 + DQO 12H', true, 'norma', '12H'::public.package_duration),
  ('XLS-06', 'NOM-002-1996 + DQO 24H', true, 'norma', '24H'::public.package_duration),
  ('XLS-07', 'NORMA 001-SEMARNAT-1996 24H', true, 'norma', '24H'::public.package_duration),
  ('XLS-08', 'NORMA 001-SEMARNAT-1996 12H', true, 'norma', '12H'::public.package_duration),
  ('XLS-09', 'NORMA 001-SEMARNAT-1996 INSTANT', true, 'norma', 'instant'::public.package_duration),
  ('XLS-10', 'NOM-003-SEMARNAT-1997 24H', true, 'norma', '24H'::public.package_duration),
  ('XLS-11', 'NOM-003-SEMARNAT-1997 12H', true, 'norma', '12H'::public.package_duration),
  ('XLS-12', 'NOM-003-SEMARNAT-1997 INSTANT', true, 'norma', 'instant'::public.package_duration),
  ('XLS-13', 'CPDs 24 PARAMETROS 24H', true, 'norma', '24H'::public.package_duration),
  ('XLS-14', 'CPDs 24 PARAMETROS 12H', true, 'norma', '12H'::public.package_duration),
  ('XLS-15', 'CPDs 24 PARAMETROS INSTANT', true, 'norma', 'instant'::public.package_duration)
on conflict (code) do update set name=excluded.name, active=true, package_type=excluded.package_type, duration=excluded.duration;

insert into public.parameters (name, unit, method_reference) values

  ('Cu', 'mg/L', 'pendiente'),
  ('As', 'mg/L', 'pendiente'),
  ('Cd', 'mg/L', 'pendiente'),
  ('CN', '?g/L', 'pendiente'),
  ('Cr VI', 'mg Cr6/L', 'pendiente'),
  ('DBO5', 'mg/L', 'pendiente'),
  ('GyA (1)', 'mg/L', 'pendiente'),
  ('MF', 'Sin unidades', 'pendiente'),
  ('Hg', 'mg/L', 'pendiente'),
  ('Ni', 'mg/L', 'pendiente'),
  ('pH', 'U. de pH', 'pendiente'),
  ('Pb', 'mg/L', 'pendiente'),
  ('S. Sed', 'ml/L', 'pendiente'),
  ('SST', 'mg/L', 'pendiente'),
  ('Temperatura', '° C', 'pendiente'),
  ('Zn', 'mg/L', 'pendiente'),
  ('GyA ponderado', 'mg/L', 'pendiente'),
  ('GyA (2)', 'mg/L', 'pendiente'),
  ('GyA (3)', 'mg/L', 'pendiente'),
  ('GyA (4)', 'mg/L', 'pendiente'),
  ('GyA (5)', 'mg/L', 'pendiente'),
  ('GyA (6)', 'mg/L', 'pendiente'),
  ('DQO', 'mgO2/L', 'pendiente'),
  ('Cloruros', 'mg/L', 'pendiente'),
  ('Col fec MG', 'NMP/100mL', 'pendiente'),
  ('Col fec (1)', 'NMP/100mL', 'pendiente'),
  ('Col fec (2)', 'NMP/100mL', 'pendiente'),
  ('Col fec (3)', 'NMP/100mL', 'pendiente'),
  ('Col fec (4)', 'NMP/100mL', 'pendiente'),
  ('Col fec (5)', 'NMP/100mL', 'pendiente'),
  ('Col fec (6)', 'NMP/100mL', 'pendiente'),
  ('Cr', 'mg/L', 'pendiente'),
  ('HH', 'H/L', 'pendiente'),
  ('NO3', 'mg N-NO3/L', 'pendiente'),
  ('NO2', 'mg/L de N-O2', 'pendiente'),
  ('N-TKN', 'mg/L', 'pendiente'),
  ('N Total', 'mg/L-N', 'pendiente'),
  ('PT', 'mg P/L', 'pendiente'),
  ('pH muestreo', 'U. de pH', 'pendiente'),
  ('Al', 'mg/L', 'pendiente'),
  ('CE', '?S/cm', 'pendiente'),
  ('Dureza T', 'mg/L-CaCO3', 'pendiente'),
  ('Dureza Ca', 'mg/L-CaCO3', 'pendiente'),
  ('SAAM', 'mg/L- SAL', 'pendiente')
on conflict (name) do update set unit=coalesce(nullif(public.parameters.unit, ''), excluded.unit);

insert into public.analysis_package_rows (package_id,row_key,label,unit,row_type,aggregation,display_order) values

  ((select id from public.analysis_packages where code='XLS-01'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-01'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-01'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-01'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-01'),'cr_vi','Cr VI','mg Cr6/L','result',null,360),
  ((select id from public.analysis_packages where code='XLS-01'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-01'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-01'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-01'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-01'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-01'),'ph','pH','U. de pH','result',null,760),
  ((select id from public.analysis_packages where code='XLS-01'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-01'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-01'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-01'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-01'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-02'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-02'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-02'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-02'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-02'),'cr_vi','Cr VI','mg Cr6/L','result',null,360),
  ((select id from public.analysis_packages where code='XLS-02'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-02'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-02'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-02'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-02'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-02'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-02'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-02'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-02'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-02'),'ph','pH','U. de pH','result',null,760),
  ((select id from public.analysis_packages where code='XLS-02'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-02'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-02'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-02'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-02'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-03'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-03'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-03'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-03'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-03'),'cr_vi','Cr VI','mg Cr6/L','result',null,360),
  ((select id from public.analysis_packages where code='XLS-03'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-03'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-03'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-03'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-03'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-03'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-03'),'gya_5','GyA (5)','mg/L','result',null,590),
  ((select id from public.analysis_packages where code='XLS-03'),'gya_6','GyA (6)','mg/L','result',null,600),
  ((select id from public.analysis_packages where code='XLS-03'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-03'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-03'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-03'),'ph','pH','U. de pH','result',null,760),
  ((select id from public.analysis_packages where code='XLS-03'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-03'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-03'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-03'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-03'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-04'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-04'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-04'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-04'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-04'),'cr_vi','Cr VI','mg Cr6/L','result',null,360),
  ((select id from public.analysis_packages where code='XLS-04'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-04'),'dqo','DQO','mgO2/L','result',null,400),
  ((select id from public.analysis_packages where code='XLS-04'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-04'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-04'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-04'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-04'),'ph','pH','U. de pH','result',null,760),
  ((select id from public.analysis_packages where code='XLS-04'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-04'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-04'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-04'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-04'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-05'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-05'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-05'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-05'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-05'),'cr_vi','Cr VI','mg Cr6/L','result',null,360),
  ((select id from public.analysis_packages where code='XLS-05'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-05'),'dqo','DQO','mgO2/L','result',null,400),
  ((select id from public.analysis_packages where code='XLS-05'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-05'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-05'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-05'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-05'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-05'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-05'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-05'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-05'),'ph','pH','U. de pH','result',null,760),
  ((select id from public.analysis_packages where code='XLS-05'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-05'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-05'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-05'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-05'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-06'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-06'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-06'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-06'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-06'),'cr_vi','Cr VI','mg Cr6/L','result',null,360),
  ((select id from public.analysis_packages where code='XLS-06'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-06'),'dqo','DQO','mgO2/L','result',null,400),
  ((select id from public.analysis_packages where code='XLS-06'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-06'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-06'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-06'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-06'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-06'),'gya_5','GyA (5)','mg/L','result',null,590),
  ((select id from public.analysis_packages where code='XLS-06'),'gya_6','GyA (6)','mg/L','result',null,600),
  ((select id from public.analysis_packages where code='XLS-06'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-06'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-06'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-06'),'ph','pH','U. de pH','result',null,760),
  ((select id from public.analysis_packages where code='XLS-06'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-06'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-06'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-06'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-06'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-07'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-07'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-07'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-07'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-07'),'cloruros','Cloruros','mg/L','result',null,200),
  ((select id from public.analysis_packages where code='XLS-07'),'col_fec_mg','Col fec MG','NMP/100mL','aggregate','media geom?trica',210),
  ((select id from public.analysis_packages where code='XLS-07'),'col_fec_1','Col fec (1)','NMP/100mL','result',null,220),
  ((select id from public.analysis_packages where code='XLS-07'),'col_fec_2','Col fec (2)','NMP/100mL','result',null,230),
  ((select id from public.analysis_packages where code='XLS-07'),'col_fec_3','Col fec (3)','NMP/100mL','result',null,240),
  ((select id from public.analysis_packages where code='XLS-07'),'col_fec_4','Col fec (4)','NMP/100mL','result',null,250),
  ((select id from public.analysis_packages where code='XLS-07'),'col_fec_5','Col fec (5)','NMP/100mL','result',null,260),
  ((select id from public.analysis_packages where code='XLS-07'),'col_fec_6','Col fec (6)','NMP/100mL','result',null,270),
  ((select id from public.analysis_packages where code='XLS-07'),'cr','Cr','mg/L','result',null,350),
  ((select id from public.analysis_packages where code='XLS-07'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-07'),'dqo','DQO','mgO2/L','result',null,400),
  ((select id from public.analysis_packages where code='XLS-07'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-07'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-07'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-07'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-07'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-07'),'gya_5','GyA (5)','mg/L','result',null,590),
  ((select id from public.analysis_packages where code='XLS-07'),'gya_6','GyA (6)','mg/L','result',null,600),
  ((select id from public.analysis_packages where code='XLS-07'),'hh','HH','H/L','result',null,630),
  ((select id from public.analysis_packages where code='XLS-07'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-07'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-07'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-07'),'no3','NO3','mg N-NO3/L','result',null,690),
  ((select id from public.analysis_packages where code='XLS-07'),'no2','NO2','mg/L de N-O2','result',null,700),
  ((select id from public.analysis_packages where code='XLS-07'),'n_tkn','N-TKN','mg/L','result',null,730),
  ((select id from public.analysis_packages where code='XLS-07'),'n_total','N Total','mg/L-N','result',null,740),
  ((select id from public.analysis_packages where code='XLS-07'),'ph','pH','U. de pH','result',null,760),
  ((select id from public.analysis_packages where code='XLS-07'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-07'),'pt','PT','mg P/L','result',null,790),
  ((select id from public.analysis_packages where code='XLS-07'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-07'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-07'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-07'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-08'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-08'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-08'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-08'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-08'),'cloruros','Cloruros','mg/L','result',null,200),
  ((select id from public.analysis_packages where code='XLS-08'),'col_fec_mg','Col fec MG','NMP/100mL','aggregate','media geom?trica',210),
  ((select id from public.analysis_packages where code='XLS-08'),'col_fec_1','Col fec (1)','NMP/100mL','result',null,220),
  ((select id from public.analysis_packages where code='XLS-08'),'col_fec_2','Col fec (2)','NMP/100mL','result',null,230),
  ((select id from public.analysis_packages where code='XLS-08'),'col_fec_3','Col fec (3)','NMP/100mL','result',null,240),
  ((select id from public.analysis_packages where code='XLS-08'),'col_fec_4','Col fec (4)','NMP/100mL','result',null,250),
  ((select id from public.analysis_packages where code='XLS-08'),'cr','Cr','mg/L','result',null,350),
  ((select id from public.analysis_packages where code='XLS-08'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-08'),'dqo','DQO','mgO2/L','result',null,400),
  ((select id from public.analysis_packages where code='XLS-08'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-08'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-08'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-08'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-08'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-08'),'hh','HH','H/L','result',null,630),
  ((select id from public.analysis_packages where code='XLS-08'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-08'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-08'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-08'),'no3','NO3','mg N-NO3/L','result',null,690),
  ((select id from public.analysis_packages where code='XLS-08'),'no2','NO2','mg/L de N-O2','result',null,700),
  ((select id from public.analysis_packages where code='XLS-08'),'n_tkn','N-TKN','mg/L','result',null,730),
  ((select id from public.analysis_packages where code='XLS-08'),'n_total','N Total','mg/L-N','result',null,740),
  ((select id from public.analysis_packages where code='XLS-08'),'ph','pH','U. de pH','result',null,760),
  ((select id from public.analysis_packages where code='XLS-08'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-08'),'pt','PT','mg P/L','result',null,790),
  ((select id from public.analysis_packages where code='XLS-08'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-08'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-08'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-08'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-09'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-09'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-09'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-09'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-09'),'cloruros','Cloruros','mg/L','result',null,200),
  ((select id from public.analysis_packages where code='XLS-09'),'col_fec_1','Col fec (1)','NMP/100mL','result',null,220),
  ((select id from public.analysis_packages where code='XLS-09'),'cr','Cr','mg/L','result',null,350),
  ((select id from public.analysis_packages where code='XLS-09'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-09'),'dqo','DQO','mgO2/L','result',null,400),
  ((select id from public.analysis_packages where code='XLS-09'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-09'),'hh','HH','H/L','result',null,630),
  ((select id from public.analysis_packages where code='XLS-09'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-09'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-09'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-09'),'no3','NO3','mg N-NO3/L','result',null,690),
  ((select id from public.analysis_packages where code='XLS-09'),'no2','NO2','mg/L de N-O2','result',null,700),
  ((select id from public.analysis_packages where code='XLS-09'),'n_tkn','N-TKN','mg/L','result',null,730),
  ((select id from public.analysis_packages where code='XLS-09'),'n_total','N Total','mg/L-N','result',null,740),
  ((select id from public.analysis_packages where code='XLS-09'),'ph','pH','U. de pH','result',null,760),
  ((select id from public.analysis_packages where code='XLS-09'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-09'),'pt','PT','mg P/L','result',null,790),
  ((select id from public.analysis_packages where code='XLS-09'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-09'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-09'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-09'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-10'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-10'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-10'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-10'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-10'),'col_fec_mg','Col fec MG','NMP/100mL','aggregate','media geom?trica',210),
  ((select id from public.analysis_packages where code='XLS-10'),'col_fec_1','Col fec (1)','NMP/100mL','result',null,220),
  ((select id from public.analysis_packages where code='XLS-10'),'col_fec_2','Col fec (2)','NMP/100mL','result',null,230),
  ((select id from public.analysis_packages where code='XLS-10'),'col_fec_3','Col fec (3)','NMP/100mL','result',null,240),
  ((select id from public.analysis_packages where code='XLS-10'),'col_fec_4','Col fec (4)','NMP/100mL','result',null,250),
  ((select id from public.analysis_packages where code='XLS-10'),'col_fec_5','Col fec (5)','NMP/100mL','result',null,260),
  ((select id from public.analysis_packages where code='XLS-10'),'col_fec_6','Col fec (6)','NMP/100mL','result',null,270),
  ((select id from public.analysis_packages where code='XLS-10'),'cr','Cr','mg/L','result',null,350),
  ((select id from public.analysis_packages where code='XLS-10'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-10'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-10'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-10'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-10'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-10'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-10'),'gya_5','GyA (5)','mg/L','result',null,590),
  ((select id from public.analysis_packages where code='XLS-10'),'gya_6','GyA (6)','mg/L','result',null,600),
  ((select id from public.analysis_packages where code='XLS-10'),'hh','HH','H/L','result',null,630),
  ((select id from public.analysis_packages where code='XLS-10'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-10'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-10'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-10'),'ph_muestreo','pH muestreo','U. de pH','result',null,770),
  ((select id from public.analysis_packages where code='XLS-10'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-10'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-10'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-10'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-11'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-11'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-11'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-11'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-11'),'col_fec_mg','Col fec MG','NMP/100mL','aggregate','media geom?trica',210),
  ((select id from public.analysis_packages where code='XLS-11'),'col_fec_1','Col fec (1)','NMP/100mL','result',null,220),
  ((select id from public.analysis_packages where code='XLS-11'),'col_fec_2','Col fec (2)','NMP/100mL','result',null,230),
  ((select id from public.analysis_packages where code='XLS-11'),'col_fec_3','Col fec (3)','NMP/100mL','result',null,240),
  ((select id from public.analysis_packages where code='XLS-11'),'col_fec_4','Col fec (4)','NMP/100mL','result',null,250),
  ((select id from public.analysis_packages where code='XLS-11'),'cr','Cr','mg/L','result',null,350),
  ((select id from public.analysis_packages where code='XLS-11'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-11'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-11'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-11'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-11'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-11'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-11'),'hh','HH','H/L','result',null,630),
  ((select id from public.analysis_packages where code='XLS-11'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-11'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-11'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-11'),'ph_muestreo','pH muestreo','U. de pH','result',null,770),
  ((select id from public.analysis_packages where code='XLS-11'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-11'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-11'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-11'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-12'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-12'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-12'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-12'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-12'),'col_fec_1','Col fec (1)','NMP/100mL','result',null,220),
  ((select id from public.analysis_packages where code='XLS-12'),'cr','Cr','mg/L','result',null,350),
  ((select id from public.analysis_packages where code='XLS-12'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-12'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-12'),'hh','HH','H/L','result',null,630),
  ((select id from public.analysis_packages where code='XLS-12'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-12'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-12'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-12'),'ph_muestreo','pH muestreo','U. de pH','result',null,770),
  ((select id from public.analysis_packages where code='XLS-12'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-12'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-12'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-12'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-13'),'al','Al','mg/L','result',null,70),
  ((select id from public.analysis_packages where code='XLS-13'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-13'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-13'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-13'),'ce','CE','?S/cm','result',null,160),
  ((select id from public.analysis_packages where code='XLS-13'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-13'),'cr_vi','Cr VI','mg Cr6/L','result',null,360),
  ((select id from public.analysis_packages where code='XLS-13'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-13'),'dqo','DQO','mgO2/L','result',null,400),
  ((select id from public.analysis_packages where code='XLS-13'),'dureza_t','Dureza T','mg/L-CaCO3','result',null,420),
  ((select id from public.analysis_packages where code='XLS-13'),'dureza_ca','Dureza Ca','mg/L-CaCO3','result',null,430),
  ((select id from public.analysis_packages where code='XLS-13'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-13'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-13'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-13'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-13'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-13'),'gya_5','GyA (5)','mg/L','result',null,590),
  ((select id from public.analysis_packages where code='XLS-13'),'gya_6','GyA (6)','mg/L','result',null,600),
  ((select id from public.analysis_packages where code='XLS-13'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-13'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-13'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-13'),'n_tkn','N-TKN','mg/L','result',null,730),
  ((select id from public.analysis_packages where code='XLS-13'),'ph_muestreo','pH muestreo','U. de pH','result',null,770),
  ((select id from public.analysis_packages where code='XLS-13'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-13'),'pt','PT','mg P/L','result',null,790),
  ((select id from public.analysis_packages where code='XLS-13'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-13'),'saam','SAAM','mg/L- SAL','result',null,830),
  ((select id from public.analysis_packages where code='XLS-13'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-13'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-13'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-14'),'al','Al','mg/L','result',null,70),
  ((select id from public.analysis_packages where code='XLS-14'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-14'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-14'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-14'),'ce','CE','?S/cm','result',null,160),
  ((select id from public.analysis_packages where code='XLS-14'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-14'),'cr_vi','Cr VI','mg Cr6/L','result',null,360),
  ((select id from public.analysis_packages where code='XLS-14'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-14'),'dqo','DQO','mgO2/L','result',null,400),
  ((select id from public.analysis_packages where code='XLS-14'),'dureza_t','Dureza T','mg/L-CaCO3','result',null,420),
  ((select id from public.analysis_packages where code='XLS-14'),'dureza_ca','Dureza Ca','mg/L-CaCO3','result',null,430),
  ((select id from public.analysis_packages where code='XLS-14'),'gya_ponderado','GyA ponderado','mg/L','aggregate','ponderado',540),
  ((select id from public.analysis_packages where code='XLS-14'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-14'),'gya_2','GyA (2)','mg/L','result',null,560),
  ((select id from public.analysis_packages where code='XLS-14'),'gya_3','GyA (3)','mg/L','result',null,570),
  ((select id from public.analysis_packages where code='XLS-14'),'gya_4','GyA (4)','mg/L','result',null,580),
  ((select id from public.analysis_packages where code='XLS-14'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-14'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-14'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-14'),'n_tkn','N-TKN','mg/L','result',null,730),
  ((select id from public.analysis_packages where code='XLS-14'),'ph_muestreo','pH muestreo','U. de pH','result',null,770),
  ((select id from public.analysis_packages where code='XLS-14'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-14'),'pt','PT','mg P/L','result',null,790),
  ((select id from public.analysis_packages where code='XLS-14'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-14'),'saam','SAAM','mg/L- SAL','result',null,830),
  ((select id from public.analysis_packages where code='XLS-14'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-14'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-14'),'zn','Zn','mg/L','result',null,1000),
  ((select id from public.analysis_packages where code='XLS-15'),'al','Al','mg/L','result',null,70),
  ((select id from public.analysis_packages where code='XLS-15'),'cu','Cu','mg/L','result',null,110),
  ((select id from public.analysis_packages where code='XLS-15'),'as','As','mg/L','result',null,140),
  ((select id from public.analysis_packages where code='XLS-15'),'cd','Cd','mg/L','result',null,150),
  ((select id from public.analysis_packages where code='XLS-15'),'ce','CE','?S/cm','result',null,160),
  ((select id from public.analysis_packages where code='XLS-15'),'cn','CN','?g/L','result',null,170),
  ((select id from public.analysis_packages where code='XLS-15'),'cr_vi','Cr VI','mg Cr6/L','result',null,360),
  ((select id from public.analysis_packages where code='XLS-15'),'dbo5','DBO5','mg/L','result',null,370),
  ((select id from public.analysis_packages where code='XLS-15'),'dqo','DQO','mgO2/L','result',null,400),
  ((select id from public.analysis_packages where code='XLS-15'),'dureza_t','Dureza T','mg/L-CaCO3','result',null,420),
  ((select id from public.analysis_packages where code='XLS-15'),'dureza_ca','Dureza Ca','mg/L-CaCO3','result',null,430),
  ((select id from public.analysis_packages where code='XLS-15'),'gya_1','GyA (1)','mg/L','result',null,550),
  ((select id from public.analysis_packages where code='XLS-15'),'mf','MF','Sin unidades','result',null,650),
  ((select id from public.analysis_packages where code='XLS-15'),'hg','Hg','mg/L','result',null,660),
  ((select id from public.analysis_packages where code='XLS-15'),'ni','Ni','mg/L','result',null,680),
  ((select id from public.analysis_packages where code='XLS-15'),'n_tkn','N-TKN','mg/L','result',null,730),
  ((select id from public.analysis_packages where code='XLS-15'),'ph_muestreo','pH muestreo','U. de pH','result',null,770),
  ((select id from public.analysis_packages where code='XLS-15'),'pb','Pb','mg/L','result',null,780),
  ((select id from public.analysis_packages where code='XLS-15'),'pt','PT','mg P/L','result',null,790),
  ((select id from public.analysis_packages where code='XLS-15'),'s_sed','S. Sed','ml/L','result',null,820),
  ((select id from public.analysis_packages where code='XLS-15'),'saam','SAAM','mg/L- SAL','result',null,830),
  ((select id from public.analysis_packages where code='XLS-15'),'sst','SST','mg/L','result',null,890),
  ((select id from public.analysis_packages where code='XLS-15'),'temperatura','Temperatura','° C','result',null,940),
  ((select id from public.analysis_packages where code='XLS-15'),'zn','Zn','mg/L','result',null,1000)
on conflict (package_id,row_key) do update set label=excluded.label, unit=excluded.unit, row_type=excluded.row_type, aggregation=excluded.aggregation, display_order=excluded.display_order;

insert into public.package_parameters (package_id, parameter_id)
select distinct r.package_id, p.id from public.analysis_package_rows r join public.parameters p on p.name=r.label
on conflict do nothing;


create or replace function public.create_analysis_order_rows_from_package(p_sample_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare v_package_id uuid; v_package_code text; v_has_template boolean;
begin
  select s.package_id, ap.code into v_package_id, v_package_code
  from public.samples s join public.analysis_packages ap on ap.id=s.package_id where s.id=p_sample_id;
  if v_package_id is null then return; end if;
  select exists(select 1 from public.analysis_package_rows where package_id=v_package_id) into v_has_template;
  if v_has_template then
    insert into public.analysis_order_rows (sample_id,row_key,label,unit,row_type,aggregation,display_order)
    select p_sample_id,row_key,label,unit,row_type,aggregation,display_order from public.analysis_package_rows where package_id=v_package_id
    on conflict (sample_id,row_key) do update set label=excluded.label,unit=excluded.unit,row_type=excluded.row_type,aggregation=excluded.aggregation,display_order=excluded.display_order;
    update public.samples set analysis_order_created_at=coalesce(analysis_order_created_at,now()) where id=p_sample_id;
  elsif v_package_code='NOM-001-2021-24H' then
    perform public.create_nom001_2021_24h_rows(p_sample_id);
  end if;
end;
$$;
create or replace function public.create_template_rows_for_sample()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  perform public.create_analysis_order_rows_from_package(new.id);
  return new;
end;
$$;
drop trigger if exists samples_create_template_rows on public.samples;
create trigger samples_create_template_rows after insert on public.samples for each row execute function public.create_template_rows_for_sample();
grant execute on function public.create_analysis_order_rows_from_package(uuid) to authenticated;
