-- Directorio del personal que participa en muestreos, análisis y emisión de informes.

create table if not exists public.laboratory_staff (
  id uuid primary key default gen_random_uuid(),
  internal_id bigint generated by default as identity unique not null,
  full_name text not null check (btrim(full_name) <> ''),
  initials text not null unique check (btrim(initials) <> ''),
  position_title text not null check (btrim(position_title) <> ''),
  functions text[] not null check (
    cardinality(functions) > 0
    and functions <@ array['analista', 'muestreador', 'revisor', 'responsable_autorizacion']::text[]
  ),
  active boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists laboratory_staff_active_name_idx
  on public.laboratory_staff(active, full_name);
create index if not exists laboratory_staff_created_by_idx
  on public.laboratory_staff(created_by);

alter table public.laboratory_staff enable row level security;

drop policy if exists "authenticated staff read laboratory personnel" on public.laboratory_staff;
create policy "authenticated staff read laboratory personnel"
on public.laboratory_staff for select to authenticated
using ((select public.current_role()) in ('administrador', 'recepcion', 'analista', 'revisor'));

drop policy if exists "administration creates laboratory personnel" on public.laboratory_staff;
create policy "administration creates laboratory personnel"
on public.laboratory_staff for insert to authenticated
with check ((select public.current_role()) in ('administrador', 'recepcion'));

drop policy if exists "administration updates laboratory personnel" on public.laboratory_staff;
create policy "administration updates laboratory personnel"
on public.laboratory_staff for update to authenticated
using ((select public.current_role()) in ('administrador', 'recepcion'))
with check ((select public.current_role()) in ('administrador', 'recepcion'));

grant select, insert, update on public.laboratory_staff to authenticated;
grant usage, select on sequence public.laboratory_staff_internal_id_seq to authenticated;
